# Generated by Django 5.0.6 on 2024-10-25 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
