# Generated by Django 5.0.6 on 2024-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificador_colab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='name',
            field=models.EmailField(max_length=64),
        ),
    ]
